### ISSUE TITLE
Session null

### ISSUE THREAD

**Issue by amirolzolkifli** [martinbean/facebook-php-sdk-laravel#1]
Hi,

I'm getting Facebook Session is NULL after authentification.

How can I fix it?

Thanks!

**Comment by martinbean** [comment]
@amirolzolkifli I can’t really diagnose without any more information. Can you post your code, and whether you’re using Laravel 4 or 5? Thanks.

**Comment by amirolzolkifli** [comment]
Hi @martinbean,

I'm using Laravel 4.2

This is the code:

    public function loginFacebook()
    {
        FacebookSession::setDefaultApplication(
            Config::get('packages/my/my-facebook.appId'),
            Config::get('packages/my/my-facebook.secret')
        );

        $redirect_url = Request::url();

        $helper = new FacebookRedirectLoginHelper( $redirect_url );

        if( $session = $helper->getSessionFromRedirect() )
        {
            $request = new FacebookRequest( $session, 'GET', '/me' );

            $user_profile = $request->execute()->getGraphObject( GraphUser::className() );
            
            // check database for user account
            $user_fb = User::whereEmail( $user_profile->getProperty('email') )->first();
            
            if( ! count( $user_fb ) )
            {
                $account = new User;
                $account->username = $user_profile->getId();
                $account->email = $user_profile->getProperty('email');
                //$account->photo = 'https://graph.facebook.com/'.$user_profile->getId().'/picture?type=large';
                $account->status = 'active';
                $account->first_name = $user_profile->getFirstName();
                $account->last_name = $user_profile->getLastName();
                $account->save();

                $profile = new UserFb;
                $profile->user_id = $account->id;
                $profile->fb_uid = $user_profile->getId();
                $profile->fb_photo = 'https://graph.facebook.com/'.$user_profile->getId().'/picture?type=large';
                $profile->fb_email = $user_profile->getProperty('email');
                $profile->fb_first_name = $user_profile->getFirstName();
                $profile->fb_last_name = $user_profile->getLastName();
                $profile->save();

                $account->attachRole( Role::whereName('user')->pluck('id') );
                
                $user_fb = $account;
                
            }
            
            Auth::login( $user_fb );
            
            //return Response::make('Hello, '. $user_profile->getProperty('email'));
            return Redirect::to('/')->with('success', 'Welcome ' . Auth::user()->first_name . '. You\'ve successfully logged in with Facebook.');
            
        }
        
        return Redirect::to( $helper->getLoginUrl(['scope' => 'public_profile, email, user_birthday']) );
    }

**Comment by amirolzolkifli** [comment]
Hi Martin,

My code is working now when I reverted the Facebook SDK version from 4.0.23 to previous version (4.0.15) (before the composer update).

**Comment by maclof** [comment]
There should be a call to $this->loadState() in the isValidRedirect() method.

Otherwise it's trying to do a check against $this->state, which will always be null.

**Comment by martinbean** [comment]
Resolved by #3.
